### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by JB-MS** [mobiusklein/mzidentml_writer#1]
Hi,

this module looks really nice and i would really like to use it, but getting it to work with Python3.4 is giving me a hard time. Are there any plans to migrate/adapt the code to Python3.4, e.g. in a new branch or repository?

Cheers,
Johannes

**Comment by mobiusklein** [comment]
I've merged this project with another, https://github.com/mobiusklein/psims, which supports writing both mzML and mzIdentML. I do plan to make this library Py3 compatible. I'll start this process today. 

Thank you for your interest.

**Comment by JB-MS** [comment]
Hi,

that sounds great! I am looking forward to use it.

Thanks!

Cheers,
Johannes

**Comment by mobiusklein** [comment]
The relevant changes have been pushed to psims:master, adding Python 3 compatibility. My Python 3 environment uses 3.5. I don't think I used any features not common to both versions. The mzIdentML API is much more complex. We can carry on conversation over there to discuss what usage should look like. I'll make a note here that this project is superseded by that one.
